FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache bash curl

COPY package.json package-lock.json ./
RUN npm ci

COPY prisma ./prisma
RUN npx prisma generate

COPY . .

EXPOSE 3000

CMD ["npx", "tsx", "watch", "src/index.ts"]
